version: '3.7'

services:
    db:
        image: postgres
        container_name: iadopt_postgres
        restart: on-failure
        environment:
          POSTGRES_PASSWORD: iadopt_db
          POSTGRES_USER: admin
          POSTGRES_DB: iadopt
        ports:
          - '5432:5432'
        volumes:
          - postgres_data:/var/lib/postgresql/data
          - ./src/db:/opt

    backend:
        container_name: iadopt_backend
        build:
          context: .
        environment:
          DATABASE_URL: postgres://admin:iadopt_db@db:5432/iadopt
          DATABASE_PW: iadopt_db
          DATABASE_USER: admin
          DATABASE_NAME: iadopt
          DATABASE_HOST: db
          DATABASE_PORT: 5432
        depends_on:
          - db
        ports:
          - '8080:8080'
        volumes:
          - ./:/opt/app
        entrypoint: "./entrypoint.sh start"

volumes:
  postgres_data:
